### ISSUE TITLE
Typo in PunkWindow.as, line 62

### ISSUE THREAD

**Issue by lucascaro** [RichardMarks/punk.ui#1]
Hi there, this punk ui is great! I'm starting to use it's really useful. thank you!

I wanted to share with you a typo I've found: in line 62 (the constructor) of PunkWindow.as there's a typo, it says draggabble instead of draggable and the result is that the window is allways draggable:

``` actionscript
public function PunkWindow(x:Number=0, y:Number=0, width:int=20, height:int=20, caption:String = "", draggabble:Boolean = true, skin:PunkSkin=null)
```

should be

``` actionscript
public function PunkWindow(x:Number=0, y:Number=0, width:int=20, height:int=20, caption:String = "", draggable:Boolean = true, skin:PunkSkin=null)
```

thanks again for the code!

**Comment by AbelToy** [comment]
Fixed, thanks!
