### ISSUE TITLE
Nested PunkPanels

### ISSUE THREAD

**Issue by AbelToy** [RichardMarks/punk.ui#16]
Let PunkPanels accept other PunkPanels without problems / bugs. Needs a lot of investigation / experimentation.

**Comment by Danik** [comment]
To me this seems very important. Having a solid basic panel component to build on would help a lot when designing aggregate components. 

I will try to get a grip on how that might work soon.

**Comment by Danik** [comment]
This now seems to work, needs testing though to make sure. Specifically the order things are added.
