### ISSUE TITLE
PunkWindow only draggable using the caption bar

### ISSUE THREAD

**Issue by AbelToy** [RichardMarks/punk.ui#20]
We should make the PunkWindow only draggable using the caption bar.

Some user suggested checking collisions with the text on it (we should then modify its width property to use the whole window, easy stuff -only add caption.width = width when it's created-).

We could also specify the caption bar height on the skin, but I guess checking collisions with the text is easier. What do you think?

**Comment by Danik** [comment]
I'm thinking maybe PunkWindow could be composed of two PunkPanels, then collision could be checked on those individually. At the moment only PunkPanel can have children though, one solution would be to let PunkUIComponent have the children-functionality, another would be to add the window's children to the world in PunkWindow.added() like so:

private var captionBarPanel:PunkPanel;
private var contentPanel:PunkPanel;

override public function added():void {
    FP.world.add(captionBarPanel);
    FP.world.add(contentPanel);
}

Or, when/if PunkPanels can have PunkPanels in them, PunkWindow could extend PunkPanel, have two PunkPanels for the caption and content areas, and then just delegate panel operations like add() and remove() to it's content panel.

Just some thoughts, I have not read all of the codebase yet so it might not be possible/practical. :)

**Comment by AbelToy** [comment]
We should then wait for nested panels I think.

**Comment by AbelToy** [comment]
Danik fixed this. 64d5f5bbc7a42536ab5e
